FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

ENV NODE_ENV=production
ENV WEBHOOK_SERCRET_DEV=${WEBHOOK_SERCRET_DEV}
ENV WEBHOOK_SECRET=${WEBHOOK_SERCRET_PROD}
ENV APP_CLIENT_ID=${CLIENT_ID}
ENV APP_CLIENT_SECRET=${CLIENT_SECRET_DEV}
ENV FX_DEV_PATH=${FX_DEV_PATH}
ENV ACCESSIFY_URL=${ACCESSIFY_URL}
ENV ACCESSIFY_PUBLIC_URL=${ACCESSIFY_PUBLIC_URL}
ENV CMP_ACCESS_TOKEN=${CMP_ACCESS_TOKEN}

EXPOSE 8000

CMD ["npm", "run", "start"]